# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A2FSwGR7DJclJjW1GnosJfxBl7pEhkk0
"""

import pandas as pd
import numpy as np
pd.__version__

ser1 = pd.Series(list("abcdefghijklmnopqrstuvwxyz"))

ser1

"""Este ejercicio hace una serie con el texto que introducimos, descomponiendola en cada caracter y luego la imprimimos"""

ser1 = pd.Series(list("abcdefghijklmnopqrstuvwxyz"))
ser2 = pd.Series(np.arange(26))

df = pd.DataFrame({"Ser1" : ser1, "Ser2" : ser2})
df.head()

"""#Limpiar datos

El objetivo de este ejercicio es seleccionar los elementos de la serie que no aparezca en el segundo.
Los datos en result es una serie que contiene true y false, true en los datos que existen dentro de ser2, false para los que no. 
En ser1[~result] muestra los datos que tengan true en el mismo index que result, mostrando solo los que no estan dentro de ser2
"""

ser1 = pd.Series([1,2,3,4,5])
ser2 = pd.Series([4,5,6,7,8])

result = ser1.isin(ser2)
ser1[~result]

"""#Convertir en matrices

El objetivo del ejercicio es convertir una serie en una matriz
"""

ser = np.random.randint(1,10,35)
df0 = pd.DataFrame({'1': ser})
df1 = df0.pivot(index= '1', columns= 'llo', values= df0)
df1