# -*- coding: utf-8 -*-
"""Copia de Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SJmYIadPg_BTLQQ75prKRar7tlwoMW0g
"""

import pandas  as pd
import numpy as np
pd.__version__

mylist = list("asdfqwezxcv")
myarr = list(range(0,len(mylist)))
ser = pd.DataFrame({"numeros" : myarr, "letras" : mylist})
ser

np.random.RandomState(100)
lista = np.random.randint(1,5,[12])
ser = pd.Series(lista)
ser

ser.value_counts()

ser[ser.isin(ser.value_counts())]

